jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml
Fixes #2, by following the docs here:
https://cloud.spring.io/spring-cloud-connectors/spring-cloud-cloud-foundry-connector.html#_rabbitmq
=> Add URIs to RabbitMQ credentials

jobs/rabbitmq-blacksmith-plans/templates/bin/configure-blacksmith
Current default puts it in redis-services instead
=> Correct default network from redis-service to rabbitmq-service

ci/release_notes.md, config/blobs.yml, packages/erlang/packaging, packages/rabbitmq/packaging
Updated RabbitMQ to 3.7 for #4
Added blob information for Erlang 21.3 and RabbitMQ 3.7.23
=> Updating Erlang and RabbitMQ versions

config/blobs.yml, jobs/rabbitmq/templates/bin/ctl, packages/erlang/packaging, packages/rabbitmq/packaging
Updating packages to Erlang 22.3 and  RabbitMQ 3.7.28
Added ERLANG_VERSION_FULL and RABBITMQ_VERSION files to track the last run RabbitMQ version
=> Updating Erlang and RabbitMQ versions to 22.3 and 3.7.28

config/blobs.yml, packages/erlang/packaging, packages/rabbitmq/packaging
* Stemcell updated to use Bionic (requires Blacksmith-genesis-kit with Bionic or Bionic stemcell manually uploaded)
* Update Erlang/OTP to 23.3.4.9
* Update RabbitMQ to 3.8.2
=> Update RabbitMQ 3.8.2 and Erlang/OTP 23.3.4.9 and Bionic Stemcell

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
Some environments were returning BOSH domain names in configs which confused RabbitMQ.  This tells BOSH to always use IP addresses
=> Add ip_address to links

jobs/rabbitmq/spec, jobs/rabbitmq/templates/env.rb
Rabbitmq control [script](jobs/rabbitmq/templates/bin/ctl) uses `/var/vcap/jobs/rabbitmq/env` for its environment variables. 
This is populated by the [env.rb](jobs/rabbitmq/templates/env.rb) and until now it had the network part hardcoded to `blacksmith`.
This essentially means that unless the service is indeed deployed under a network named `blacksmith`, rabbitmq start will fail with the following nxdomain error:
```
09:56:34.297 [error] BOOT FAILED
BOOT FAILED
09:56:34.298 [error] ===========
===========
09:56:34.298 [error] ERROR: epmd error for host a97c0f54-a6c4-40f2-87a1-c323b03d78cd.standalone.blacksmith.rabbitmq-standalone-fa37ea67-7927-4076-af1c-d14817e6869e.bosh: nxdomain (non-existing domain)
ERROR: epmd error for host …
```
=> added dynamic backed by default rabbitmq network infromation

jobs/rabbitmq-blacksmith-plans/spec, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
standalone plan.
- addition of routing release for route register
- addition of dns-alias release for dns-alias
- route register job links to spec variables to fill in missing values.
- addition of documentation in the spec for for plans
- addition of documetnation in the spec of rabbitmq
- dashboard DNS resolves to DNS name for deployment + cf system
domain
- skeleton for TLS setup waiting for future feature implenetation
=>  Added in plan expansion to allow users to use rabbitmq dashboard with

config/blobs.yml, config/final.yml, jobs/rabbitmq-blacksmith-plans/spec, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/meta.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/tls/blacksmith_rabbitmq_services.ca, jobs/rabbitmq-blacksmith-plans/templates/tls/loggregator.ca, jobs/rabbitmq-blacksmith-plans/templates/tls/loggregator.crt, jobs/rabbitmq-blacksmith-plans/templates/tls/loggregator.key, jobs/rabbitmq/spec, jobs/rabbitmq/templates/bin/post-start
The proposed changes allow for standalone rmq service to be deployed with:  
* [rabbitmq-metrics-emitter-release](https://github.com/starkandwayne/rabbitmq-metrics-emitter-release) along with its dependencies 
* [bpm-release](https://github.com/cloudfoundry/bpm-release) and 
* [loggregator-agent-release](https://github.com/cloudfoundry/loggregator-agent-release).
Summary
* It depends on `blacksmith_services_ca` CA certificate which is created with [blacksmith-boshrelease](https://github.com/blacksmith-community/blacksmith-boshrelease/pull/18). 
* It creates a number of `meta` values and certificate `variables` that are fed conveniently  as jobs properties. 
* It creates a number of certificate template files which are populated through properties
=> Add autoscaling metrics based on queue depth

jobs/rabbitmq/spec
`rabbitmq.vhost` already appears on lines [63-65](https://github.com/blacksmith-community/rabbitmq-forge-boshrelease/blob/master/jobs/rabbitmq/spec#L63-L65)
=> removed dual vhost reference on spec

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml
Deploying a cluster plan produces the following error on blacksmith:
```
ERROR [9b6836f4-6f4d-479f-b534-483622ee9f17] failed to merge service deployment manifest with credentials.yml: 3 error(s) detected:
- $.credentials.dashboard_url: Unable to resolve `credentials.hostnames.0`: $.credentials.hostnames [=(( grab jobs.standalone/0.ips ))] is a scalar (not a map or a list)
- $.credentials.hostname: Unable to resolve `jobs.standalone/0.ips.0`: `$.jobs.standalone/0` could not be found in the datastructure
- $.credentials.hostnames: Unable to resolve `jobs.standalone/0.ips`: `$.jobs.standalone/0` could not be found in the datastructure
```
This is due to pointing `hostnames` and `hostname` to `standalone` which is not present on the cluster plan. The proposed fix replaces the reference with …
=> Fixes failure to merge service deployment manifest

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/spec, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
Allow for jobs (previously bellow route_registrar.enabled) to remain unaffected (not considered addons) when `route_registrar.enabled` is set to true.
=> route registrar and spec cleanup

jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml
* Moves the crt references from meta.rabbitmq to the job's specification
* Adds meta for the `environment` and `bosh_env`
* Adds variables for the certificate creation
=> cluster crt variables and properties

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml
Adds access to rabbitmq cluster dashboard though a routable dns entry
=> dashboard url based on DNS

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml
* Unique dashboard url including `id`
* `core_network` param
* routing, bosh-dns-aliases and bpm releases
=> route registrar and dependencies for cluster plan

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml, jobs/rabbitmq/templates/config/rabbitmq.conf.erb
* Disables tcp listener (5672) when tls is enabled.
* amqp connection details on `credentials.yml` only appear when required.
=> disables listener and amqp when required

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/init, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/init, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml, jobs/rabbitmq/spec, jobs/rabbitmq/templates/bin/post-start, jobs/rabbitmq/templates/env.rb
* updates `init` script to create an additional `management` user on vault
* updates `manifest.yml` to:
* pull those credentials from vault
* provide them as a property to the `rabbitmq` job under `management.user` and `management.pass` respectively
* updates `env.rb` to export env vars for the management user using `rabbitmq` job properties.
* updates `post-start` script to create the user on rabbitmq using the information provided on `env.rb`
* updates `credentilas.yml` to display the management user credentials
=> add Management user/fix cluster admin/cleanup

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq/spec, jobs/rabbitmq/templates/config/rabbitmq.conf.erb
Adds releases to be used along with autoscaling based on queue depth for cluster plans.
Node configuration for cluster plan expects a `cluster` property.
=> releases for as on qdepth/plan property

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml, jobs/rabbitmq/templates/bin/post-start, jobs/rabbitmq/templates/env.rb
* Add `api_url` on credentials to be used in future implementation of binding using dynamic credentials
* Exports plan type as environment variable in the deployed service instance
* Guest user deletion is based on plan being `standalone`
=> api_url plan type and guest user

ci/release_notes.md, jobs/rabbitmq-blacksmith-plans/spec, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/meta.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/tls/loggregator.ca, jobs/rabbitmq-blacksmith-plans/templates/tls/loggregator.crt, jobs/rabbitmq-blacksmith-plans/templates/tls/loggregator.key, jobs/rabbitmq/templates/config/rabbitmq.conf.erb
* Expects `rabbitmq-autoscale` as a distinct feature from blacksmith-genesis-kit deployment to enable autoscaling based on queue depth. 
* When `rabbitmq-tls` is used unless `rabbitmq-dual-mode` is also used it ensures communication is allowed only through tls. 
* Credentials on blacksmith UI and those provided during bind and service-key include endpoints related to the features selected. 
* Job's templates are updated to be populated only when the corresponding features are selected.
=> As tl feature

jobs/rabbitmq-blacksmith-plans/spec, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/service.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
When the application bound to rabbitmq makes a call to rabbitmq service instance using verify_peer_value or equivalent, the connection fails due to the certificate returned having a dns record as a SAN when compared to the call which is made against the IP:
To address this, the logic behind the communication to the service instance was changed to rely on the DNS record consumed by the provided rabbitmq-san. jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml was added a dnsname key which should be populated by the internal .bosh dns record.
https://github.com/blacksmith-community/blacksmith/pull/39/files added `params.hostname`
With the params.hostname value available to us, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/credentials.yml and …
=> Bosh Links, SAN and creds

ci/manifest.yml, config/blobs.yml, jobs/rabbitmq-blacksmith-plans/spec, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml, packages/erlang/packaging, packages/rabbitmq/packaging
Changes include:
* the ability to use the parameter   `cf: nats_tls_only: true` which allows for required tls communication with nats on newer cf-deployments
* defaults stemcell to ubuntu-jammy
* updates rabbitmq to 3.12
* updates erlang to 25.3.2.2
* updates included bosh-releases
=> Update cf deployment

jobs/rabbitmq/templates/bin/ctl
[Bugs]
* Addresses an issue where rabbitmq would fail to start through monit due to its failure to identify the version in use @itsouvalas
=> update version identification

jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/init, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/init, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
Currently when a new service instance is created, it uses "insecure-erlang-cookie" as its erlang cookie value. This fix randomly generates a cookie each time a service is created
=> Randomly generate erlang cookie for service instances

ci/release_notes.md, config/blobs.yml, packages/erlang/packaging, packages/rabbitmq/packaging
* Updates RabbitMQ to version 3.13.3
* Update Erlang/OTP to version 26.2.5
=> Update RabbitMQ versions

jobs/rabbitmq-blacksmith-plans/spec, jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml, jobs/rabbitmq/templates/bin/ctl, jobs/rabbitmq/templates/env.rb
- Introduced a `plugins` property in `rabbitmq-blacksmith-plans/spec` for specifying a list of RabbitMQ plugins to enable.
- Updated cluster and standalone manifest templates to include the `plugins` property.
- Modified `ctl` script to handle the enabling of specified plugins during the startup process.
- Adjusted `RABBITMQ_EVAL_TIMEOUT` in `env.rb` from 60 to 90 seconds.
=> Add support for enabling custom RabbitMQ plugins

jobs/rabbitmq/spec
Rabbitmq-forge 1.2.5 couldn't fetch plugins from the manifest because the plugins property wasn't declared in jobs/rabbitmq/spec.
=> declared plugins property in rabbitmq/spec file to enable plugins

jobs/rabbitmq-blacksmith-plans/templates/plans/cluster/manifest.yml, jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
- Added new properties to the standalone and cluster plans to support log-cache integration
- Introduced bosh-dns alias for log-cache
=> update rmq forge manifest for log-cache
